# Generated by Django 3.1.14 on 2022-03-01 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('table_type', models.CharField(choices=[('met', '事实表'), ('dim', '维度表')], default=('met', '事实表'), max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_type', models.CharField(choices=[('IJ', '(INNER) JOIN'), ('LJ', 'LEFT (OUTER) JOIN'), ('RJ', 'RIGHT (OUTER) JOIN'), ('FJ', 'FULL (OUTER) JOIN')], default=('IJ', '(INNER) JOIN'), max_length=16)),
                ('join_condition', models.TextField()),
                ('left_table_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='left_table_name', to='graphql_api.table')),
                ('right_table_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='right_table_name', to='graphql_api.table')),
            ],
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graphql_api.table')),
            ],
        ),
    ]
