# Generated by Django 3.1.14 on 2022-03-03 03:10

from django.db import migrations, models
import django.db.models.deletion
import graphql_api.constants.constant


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('alias', models.CharField(max_length=32, unique=True)),
                ('table_type', models.CharField(choices=[('DWD', '事实表'), ('DIM', '维度表')], default=graphql_api.constants.constant.TableTypes['DWD'], max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_type', models.CharField(choices=[('inner join', 'NNER JOIN'), ('left join', 'LEFT JOIN'), ('right join', 'RIGHT JOIN'), ('full join', 'FULL JOIN')], default=('inner join', 'NNER JOIN'), max_length=16)),
                ('join_condition', models.TextField()),
                ('left_table_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='left_table_name', to='graphql_api.table')),
                ('right_table_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='right_table_name', to='graphql_api.table')),
            ],
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graphql_api.table')),
            ],
        ),
    ]
