# Generated by Django 3.1.14 on 2022-03-03 04:28

from django.db import migrations, models
import graphql_api.constants.constant


class Migration(migrations.Migration):

    dependencies = [
        ('graphql_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='join_type',
            field=models.CharField(choices=[('INNER_JOIN', 'inner join'), ('LEFT_JOIN', 'left join'), ('RIGHT_JOIN', 'right join'), ('FULL_JOIN', 'full join')], default=graphql_api.constants.constant.JoinTypes['INNER_JOIN'], max_length=16),
        ),
    ]
