# Generated by Django 3.1.14 on 2022-03-02 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphql_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='table_type',
            field=models.CharField(choices=[('dwd', '事实表'), ('dim', '维度表')], default=('dwd', '事实表'), max_length=32),
        ),
    ]
