# Generated by Django 3.1.14 on 2022-03-09 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphql_api', '0002_table_ref_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='ref_table',
        ),
        migrations.AlterField(
            model_name='table',
            name='alias',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
    ]
