# Generated by Django 3.1.14 on 2022-03-03 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphql_api', '0002_auto_20220303_0428'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='relationship',
            unique_together={('left_table_name', 'right_table_name')},
        ),
    ]
