# Generated by Django 3.1.14 on 2022-03-20 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphql_api', '0002_auto_20220319_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='urn',
            field=models.CharField(editable=False, max_length=512, primary_key=True, serialize=False),
        ),
    ]
