# Generated by Django 3.1.14 on 2022-03-20 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphql_api', '0003_auto_20220320_0444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='name',
            field=models.CharField(db_index=True, max_length=128, unique=True),
        ),
    ]
