# Generated by Django 3.1.14 on 2022-03-04 05:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphql_api', '0005_auto_20220304_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='name',
            field=models.CharField(db_index=True, max_length=128, unique=True, validators=[django.core.validators.RegexValidator('^[a-z][_a-z0-9]{4,}$')]),
        ),
    ]
