# Generated by Django 3.1.14 on 2022-03-04 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphql_api', '0006_auto_20220304_0536'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='relationship',
            unique_together=set(),
        ),
    ]
