# Generated by Django 3.1.14 on 2022-03-05 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphql_api', '0017_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
