# Generated by Django 3.1.14 on 2022-03-07 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphql_api', '0020_auto_20220307_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='join_condition',
            field=models.TextField(default='{{ l }}.foreign_key = {{ r }}.id'),
        ),
    ]
